[package]
name = "ahqstore_gh_hash"
version = "1.2.0"
edition = "2021"
license = "MIT"
authors = ["AHQ Store"]
description = "Generate AHQ Store GH Hash"
readme = "README.md"
repository = "https://github.com/ahqstore/gh_hash"
rust-version = "1.70"

[dependencies]
sha256 = "1"
